language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

after_success: skip

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
    - script:
        - julia --project=docs/pdf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/pdf/ docs/pdf/make.jl
      name: "PDF"
      after_success: skip
      services: docker