language: julia

os:
  - linux

julia:
  - 1.2

matrix:
  allow_failures:
    - julia: nightly

after_success: skip

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip


notifications:
  email: true